linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - lll

issues:
  exclude-rules:
    - path: 'pkg/pb/'
      linters:
        - lll
