// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: crypt/v1/crypt_service.proto

package cryptv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CryptService_EncryptFile_FullMethodName = "/crypt.v1.CryptService/EncryptFile"
)

// CryptServiceClient is the client API for CryptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptServiceClient interface {
	EncryptFile(ctx context.Context, in *EncryptFileRequest, opts ...grpc.CallOption) (*EncryptFileResponse, error)
}

type cryptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptServiceClient(cc grpc.ClientConnInterface) CryptServiceClient {
	return &cryptServiceClient{cc}
}

func (c *cryptServiceClient) EncryptFile(ctx context.Context, in *EncryptFileRequest, opts ...grpc.CallOption) (*EncryptFileResponse, error) {
	out := new(EncryptFileResponse)
	err := c.cc.Invoke(ctx, CryptService_EncryptFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptServiceServer is the server API for CryptService service.
// All implementations must embed UnimplementedCryptServiceServer
// for forward compatibility
type CryptServiceServer interface {
	EncryptFile(context.Context, *EncryptFileRequest) (*EncryptFileResponse, error)
	mustEmbedUnimplementedCryptServiceServer()
}

// UnimplementedCryptServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCryptServiceServer struct {
}

func (UnimplementedCryptServiceServer) EncryptFile(context.Context, *EncryptFileRequest) (*EncryptFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptFile not implemented")
}
func (UnimplementedCryptServiceServer) mustEmbedUnimplementedCryptServiceServer() {}

// UnsafeCryptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptServiceServer will
// result in compilation errors.
type UnsafeCryptServiceServer interface {
	mustEmbedUnimplementedCryptServiceServer()
}

func RegisterCryptServiceServer(s grpc.ServiceRegistrar, srv CryptServiceServer) {
	s.RegisterService(&CryptService_ServiceDesc, srv)
}

func _CryptService_EncryptFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptServiceServer).EncryptFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptService_EncryptFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptServiceServer).EncryptFile(ctx, req.(*EncryptFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptService_ServiceDesc is the grpc.ServiceDesc for CryptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypt.v1.CryptService",
	HandlerType: (*CryptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptFile",
			Handler:    _CryptService_EncryptFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crypt/v1/crypt_service.proto",
}
